packages:
  - "packages/*"
  - "packages/protocol/crank"
  - "apps/*"

allowBuilds:
  '@reown/appkit': set this to true or false
  bigint-buffer: true
  bufferutil: false
  esbuild: true
  keccak: set this to true or false
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
