skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
tidepay = "DfAycPzXuSu4EzqfAprZ11S8oQZ6nucuRniFNrNaK5CQ"

[programs.devnet]
tidepay = "DfAycPzXuSu4EzqfAprZ11S8oQZ6nucuRniFNrNaK5CQ"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
